### ISSUE TITLE
Blacklists and whitelists cause NullPointerException

### ISSUE THREAD

**Issue by hemed** [eea/eea.elasticsearch.river.rdf#9]
Hi,
I have tried to use whitelist as exactly described in the README file but I get NullPointerException and no data was indexed.  Any advice? Please see below from the log file. 

Exception in thread "elasticsearch[Hitman][eea_rdf_river(document)][T#1]" java.lang.NullPointerException
        at org.elasticsearch.river.eea_rdf.support.Harvester.addModelToES(Harvester.java:499)
        at org.elasticsearch.river.eea_rdf.support.Harvester.harvestWithConstruct(Harvester.java:444)
        at org.elasticsearch.river.eea_rdf.support.Harvester.harvestFromEndpoint(Harvester.java:454)
        at org.elasticsearch.river.eea_rdf.support.Harvester.runIndexAll(Harvester.java:385)
        at org.elasticsearch.river.eea_rdf.support.Harvester.run(Harvester.java:225)
        at java.lang.Thread.run(Thread.java:724)

**Comment by hemed** [comment]
@iulia-pasov Thanks for the reply. Unfortunately our sparql endpoint is not public available yet, so you will not be able to see the query results. But I will test again with the latest rdf river plugin ..

**Comment by mihaibivol** [comment]
@hemed Is this issue stil occuring?

**Comment by hemed** [comment]
Have tried with the latest river and it seems to be working well. Thanks for the nice project.
